config/routes.rb
Rails.application.routes.draw do
  get "/books", to: "books#index"
  get "/books/show"
  get "/books/new", to: "books#new"
  post "/books", to: "books#create"
  get "/books/:id/edit", to: "books#edit", as: :edit_books
  patch '/books/:id', to: 'books#update', as: :book
  delete '/books/:id', to: 'books#destroy'
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
  def create
    # Retrieve the book parameters that we submit in the form
    title = params[:title]
    author = params[:author]
    description = params[:description]

    # Create a new record in the database with this parameters
    Book.create(title: title, author: author, description: description)

    # And then redirect to the index page
    redirect_to books_path
  end

  def edit
    # Retrieve the current book
    @book = Book.find(params[:id])
  end

  def update
    # Retrieve the current book
    @book = Book.find(params[:id])

    # update the record in the database with this parameters
    @book.update(title: params[:book][:title], author: params[:book][:author], description: params[:book][:description])

    # And then redirect to the index page
    redirect_to books_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

<%= link_to "Back to Books' List", books_path %>
<%= form_with model: @book do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :author %>
  <%= form.text_field :author %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <%= form.submit %>
<% end %>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>
<div data-controller="books">
  <%= button_to "Create New Book", books_new_path, method: :get %>
  <% Book.all.each do |book| %>
    <p><%= book.title %></p>
    <p><%= book.author %></p>
    <p><%= book.description %></p>
    <p><%= book.reading_status %></p>
    <%= button_to 'Edit Book', edit_books_path(book), method: :get %>
    <%= button_to 'Delete', book, method: :delete, data: { action: "click->books#delete" } %>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

<%= link_to "Back to Books' List", books_path %>

<%= form_with url: books_path do |form| %>
  <%= form.label :title, "Title:" %>
  <%= form.text_field :title %>
  <%= form.label :author, "Author:" %>
  <%= form.text_field :author %>
  <%= form.label :description, "Description:" %>
  <%= form.text_field :description %>
  <%= form.submit %>
<% end %>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7 Bookshelf App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>